sudo: required
services:
  - docker

before_install:
  - docker build -t vladimirkuchinskiy/simple-docker-production -f Dockerfile.dev .

script:
  - docker run vladimirkuchinskiy/simple-docker-production npm run ci-test
