sudo: required
services:
  - docker

before_install:
  - docker build -t vladimirkuchinskiy/simple-docker-production -f Dockerfile.dev .

script:
  - docker run vladimirkuchinskiy/simple-docker-production npm run ci-test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-446655339702"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secret: $AWS_SECRET_KEY
